version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "flamingquaks"
    assignees:
      - "flamingquaks"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black*"
          - "flake8*"
          - "mypy*"
          - "isort*"
      production-dependencies:
        patterns:
          - "click*"
          - "pyyaml*"
          - "jinja2*"
          - "pydantic*"
