# Site settings
title: PrompTrek
description: Taking your AI editor configurations on a journey across every platform - manage prompts, MCP servers, custom commands, autonomous agents, and event hooks from one universal source.
tagline: Taking your AI editor configurations on a journey across every platform!
url: "https://promptrek.ai"
baseurl: ""
logo: /assets/promptrek-logo-with-text.png

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
header_pages:
  - index.md
  - quick-start.md
  - user-guide.md
  - contributing.md
  - feedback.md

# GitHub repository
github_username: flamingquaks
repository: flamingquaks/promptrek

# Social links
github_url: https://github.com/flamingquaks/promptrek
issues_url: https://github.com/flamingquaks/promptrek/issues

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
