name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Install uv
        uses: astral-sh/setup-uv@v1
    
      - name: Set up Python
        run: uv python install 3.11
    
      - name: Install dependencies
        run: |
          uv sync --extra dev
    
      - name: Run full test suite
        run: |
          uv run pytest tests/ --cov=src/promptrek --cov-fail-under=80

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Install uv
        uses: astral-sh/setup-uv@v1
    
      - name: Set up Python
        run: uv python install 3.11
    
      - name: Install build dependencies
        run: |
          uv add --extra dev build twine
          uv sync --extra dev
    
      - name: Build package
        run: |
          uv build
    
      - name: Check package
        run: |
          uv run twine check dist/*
    
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  publish-pypi:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
    
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
